name: news_api
description: A Dart API Client for the News API.
version: 1.0.0+1
homepage:

environment:
  sdk: ">=2.17.0-31.0.dev <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.4.0
  http: ^0.13.4

dev_dependencies:
  coverage: ^1.0.3
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
  mocktail: ^0.2.0
  test: ^1.16.4

flutter:

